# Analyse de volumétrie DuckDB — version corrigée

Ce notebook :
- convertit le CSV en Parquet si besoin ;
- enlève la colonne parasite `column56` avant l'analyse ;
- calcule la volumétrie globale ;
- mesure les nulls par colonne ;
- mesure les doublons **exacts de lignes** avec une requête corrigée ;
- montre **des exemples de lignes dupliquées** pour voir si les doublons portent seulement des `NULL` ou aussi d'autres valeurs ;
- relie les colonnes problématiques au dictionnaire métier quand c'est utile.

Point important :
- un **null** = une valeur manquante dans une colonne ;
- un **doublon** = deux lignes ou plus strictement identiques sur **toutes** les colonnes analysées ;
- ce n'est donc **pas du tout la même chose**.

In [1]:
import duckdb
import pandas as pd
from pathlib import Path

csv_file = Path("A202505.csv")
parquet_file = Path("A202505.parquet")
clean_parquet_file = Path("A202505_clean.parquet")
dictionary_file = Path("2024_descriptif-variables_open-damir-base-complete.xlsx")

csv_delim = ";"
csv_header = True

con = duckdb.connect()

print("DuckDB version :", duckdb.__version__)
print("CSV :", csv_file.resolve())
print("Parquet source :", parquet_file.resolve())
print("Parquet nettoyé :", clean_parquet_file.resolve())
print("Dictionnaire présent :", dictionary_file.exists())

DuckDB version : 1.5.1
CSV : /Users/la_brioche/kDrive/Master M1 Drive/S2/Projet FIN/A202505.csv
Parquet source : /Users/la_brioche/kDrive/Master M1 Drive/S2/Projet FIN/A202505.parquet
Parquet nettoyé : /Users/la_brioche/kDrive/Master M1 Drive/S2/Projet FIN/A202505_clean.parquet
Dictionnaire présent : False

## 1. Conversion CSV → Parquet

Cette cellule ne reconvertit pas le CSV si le Parquet existe déjà.

In [2]:
if parquet_file.exists():
    print(f"Le fichier Parquet existe déjà : {parquet_file}")
else:
    if not csv_file.exists():
        raise FileNotFoundError(f"Fichier introuvable : {csv_file}")

    con.execute(f'''
        COPY (
            SELECT *
            FROM read_csv_auto(
                '{csv_file.as_posix()}',
                delim='{csv_delim}',
                header={str(csv_header).lower()}
            )
        )
        TO '{parquet_file.as_posix()}' (FORMAT PARQUET)
    ''')

    print(f"Conversion terminée : {parquet_file}")

Le fichier Parquet existe déjà : A202505.parquet

## 2. Nettoyage minimal avant analyse

`column56` est supprimée avant l'analyse :
- elle est entièrement vide ;
- elle vient très probablement d'un séparateur final en trop ou d'un export CSV imparfait.

In [4]:
schema_source_df = con.execute(f"DESCRIBE SELECT * FROM '{parquet_file.as_posix()}'").df()
source_columns = schema_source_df["column_name"].tolist()

if "column56" in source_columns:
    con.execute(f'''
        COPY (
            SELECT * EXCLUDE (column56)
            FROM '{parquet_file.as_posix()}'
        )
        TO '{clean_parquet_file.as_posix()}' (FORMAT PARQUET)
    ''')
    print("Parquet nettoyé créé sans column56.")
else:
    con.execute(f'''
        COPY (
            SELECT *
            FROM '{parquet_file.as_posix()}'
        )
        TO '{clean_parquet_file.as_posix()}' (FORMAT PARQUET)
    ''')
    print("Aucune column56 détectée : copie simple du parquet source.")

table_ref = clean_parquet_file.as_posix()
print("Table analysée :", table_ref)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Parquet nettoyé créé sans column56.
Table analysée : A202505_clean.parquet

## 3. Aperçu rapide du jeu de données analysé

In [5]:
preview_df = con.execute(f"SELECT * FROM '{table_ref}' LIMIT 10").df()
preview_df

,FLX_ANN_MOI,ORG_CLE_REG,AGE_BEN_SNDS,BEN_RES_REG,BEN_CMU_TOP,BEN_QLT_COD,BEN_SEX_COD,DDP_SPE_COD,ETE_CAT_SNDS,ETE_REG_COD,...,PSE_ACT_CAT,PSE_SPE_SNDS,PSE_STJ_SNDS,PRE_INS_REG,PSP_ACT_SNDS,PSP_ACT_CAT,PSP_SPE_SNDS,PSP_STJ_SNDS,TOP_PS5_TRG,ETB_DCS_MCO
0,202505,76,70,76,1,1,2,0,1101,76,...,0,0,2,99,0,0,1,2,1,M
1,202505,11,70,11,0,1,1,121,9999,99,...,7,0,1,11,0,1,1,1,1,Z
2,202505,11,30,11,0,1,2,45,1107,11,...,0,0,2,99,0,99,0,9,1,S
3,202505,52,50,52,0,1,2,121,9999,99,...,3,0,1,99,0,0,42,2,1,Z
4,202505,11,80,11,1,1,2,121,9999,99,...,7,0,1,99,0,0,1,2,1,Z
5,202505,76,70,76,0,1,1,121,9999,99,...,6,0,1,76,0,1,1,1,1,Z
6,202505,11,70,11,0,1,2,0,1102,11,...,0,4,2,99,0,0,1,2,1,C
7,202505,32,80,32,0,1,2,121,9999,99,...,1,1,1,32,0,1,1,1,1,Z
8,202505,99,80,99,0,1,2,121,9999,99,...,2,0,1,99,0,0,31,2,1,Z
9,202505,11,80,76,0,1,2,121,9999,99,...,6,0,1,76,0,1,12,1,1,Z

In [6]:
schema_df = con.execute(f"DESCRIBE SELECT * FROM '{table_ref}'").df()
schema_df

     column_name column_type null   key default extra
0    FLX_ANN_MOI      BIGINT  YES  None    None  None
1    ORG_CLE_REG      BIGINT  YES  None    None  None
2   AGE_BEN_SNDS      BIGINT  YES  None    None  None
3    BEN_RES_REG      BIGINT  YES  None    None  None
4    BEN_CMU_TOP      BIGINT  YES  None    None  None
5    BEN_QLT_COD      BIGINT  YES  None    None  None
6    BEN_SEX_COD      BIGINT  YES  None    None  None
7    DDP_SPE_COD      BIGINT  YES  None    None  None
8   ETE_CAT_SNDS      BIGINT  YES  None    None  None
9    ETE_REG_COD      BIGINT  YES  None    None  None
10  ETE_TYP_SNDS      BIGINT  YES  None    None  None
11   ETP_REG_COD      BIGINT  YES  None    None  None
12  ETP_CAT_SNDS      BIGINT  YES  None    None  None
13   MDT_TYP_COD      BIGINT  YES  None    None  None
14       MFT_COD      BIGINT  YES  None    None  None
15   PRS_FJH_TYP      BIGINT  YES  None    None  None
16   PRS_ACT_COG      DOUBLE  YES  None    None  None
17   PRS_ACT_NBR      BIGINT  YES  None    None  None
18   PRS_ACT_QTE      BIGINT  YES  None    None  None
19   PRS_DEP_MNT      DOUBLE  YES  None    None  None
20   PRS_PAI_MNT      DOUBLE  YES  None    None  None
21   PRS_REM_BSE      DOUBLE  YES  None    None  None
22   PRS_REM_MNT      DOUBLE  YES  None    None  None
23   FLT_ACT_COG      DOUBLE  YES  None    None  None
24   FLT_ACT_NBR      BIGINT  YES  None    None  None
25   FLT_ACT_QTE      BIGINT  YES  None    None  None
26   FLT_PAI_MNT      DOUBLE  YES  None    None  None
27   FLT_DEP_MNT      DOUBLE  YES  None    None  None
28   FLT_REM_MNT      DOUBLE  YES  None    None  None
29       SOI_ANN     VARCHAR  YES  None    None  None
30       SOI_MOI     VARCHAR  YES  None    None  None
31       ASU_NAT      BIGINT  YES  None    None  None
32       ATT_NAT      BIGINT  YES  None    None  None
33       CPL_COD      BIGINT  YES  None    None  None
34   CPT_ENV_TYP      BIGINT  YES  None    None  None
35   DRG_AFF_NAT      BIGINT  YES  None    None  None
36   ETE_IND_TAA      BIGINT  YES  None    None  None
37       EXO_MTF      BIGINT  YES  None    None  None
38       MTM_NAT      BIGINT  YES  None    None  None
39       PRS_NAT      BIGINT  YES  None    None  None
40   PRS_PPU_SEC      BIGINT  YES  None    None  None
41   PRS_REM_TAU      DOUBLE  YES  None    None  None
42   PRS_REM_TYP      BIGINT  YES  None    None  None
43   PRS_PDS_QCP      BIGINT  YES  None    None  None
44   EXE_INS_REG      BIGINT  YES  None    None  None
45  PSE_ACT_SNDS      BIGINT  YES  None    None  None
46   PSE_ACT_CAT      BIGINT  YES  None    None  None
47  PSE_SPE_SNDS      BIGINT  YES  None    None  None
48  PSE_STJ_SNDS      BIGINT  YES  None    None  None
49   PRE_INS_REG      BIGINT  YES  None    None  None
50  PSP_ACT_SNDS      BIGINT  YES  None    None  None
51   PSP_ACT_CAT      BIGINT  YES  None    None  None
52  PSP_SPE_SNDS      BIGINT  YES  None    None  None
53  PSP_STJ_SNDS      BIGINT  YES  None    None  None
54   TOP_PS5_TRG      BIGINT  YES  None    None  None
55   ETB_DCS_MCO     VARCHAR  YES  None    None  None

## 4. Métadonnées globales

On calcule :
- le nombre de lignes ;
- le nombre de colonnes ;
- le nombre total de cellules ;
- le nombre total de cellules nulles ;
- le pourcentage global de nulls.

In [7]:
table_name = "volumetrie_tmp"
con.execute(f"CREATE OR REPLACE TEMP VIEW {table_name} AS SELECT * FROM '{table_ref}'")

columns_df = con.execute(f"DESCRIBE SELECT * FROM {table_name}").df()
columns = columns_df["column_name"].tolist()
column_types = dict(zip(columns_df["column_name"], columns_df["column_type"]))

nb_colonnes = len(columns)
nb_lignes = con.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]

null_exprs = [f'SUM(CASE WHEN "{col}" IS NULL THEN 1 ELSE 0 END) AS "{col}"' for col in columns]
nulls_wide_df = con.execute(f"SELECT {', '.join(null_exprs)} FROM {table_name}").df()

nulls_long_df = (
    nulls_wide_df.T
    .reset_index()
    .rename(columns={"index": "column_name", 0: "null_count"})
)

nulls_long_df["null_count"] = nulls_long_df["null_count"].astype("int64")
nulls_long_df["null_pct"] = (nulls_long_df["null_count"] / nb_lignes * 100).round(4)
nulls_long_df["column_type"] = nulls_long_df["column_name"].map(column_types)
nulls_long_df = nulls_long_df[["column_name", "column_type", "null_count", "null_pct"]].sort_values(
    by=["null_count", "column_name"], ascending=[False, True]
).reset_index(drop=True)

nb_null_total = int(nulls_long_df["null_count"].sum())
nb_cellules = int(nb_lignes * nb_colonnes)
pct_null_global = round((nb_null_total / nb_cellules * 100), 4) if nb_cellules else 0.0

global_df = pd.DataFrame([{
    "nb_lignes": nb_lignes,
    "nb_colonnes": nb_colonnes,
    "nb_cellules_total": nb_cellules,
    "nb_null_total": nb_null_total,
    "pct_null_global": pct_null_global
}])

global_df

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   nb_lignes  nb_colonnes  nb_cellules_total  nb_null_total  pct_null_global
0   34167564           56         1913383584        7908586           0.4133

## 5. Nulls par colonne

Ce tableau permet d'identifier les colonnes réellement problématiques.
- Un taux de null élevé peut signaler un problème technique.
- Mais il peut aussi être **normal métier** si le dictionnaire explique que la variable n'est pas alimentée sur tout le périmètre.

In [8]:
nulls_long_df

     column_name column_type  null_count  null_pct
0    PRS_ACT_NBR      BIGINT     4120235   12.0589
1    FLT_ACT_NBR      BIGINT     3788351   11.0876
2   AGE_BEN_SNDS      BIGINT           0    0.0000
3        ASU_NAT      BIGINT           0    0.0000
4        ATT_NAT      BIGINT           0    0.0000
5    BEN_CMU_TOP      BIGINT           0    0.0000
6    BEN_QLT_COD      BIGINT           0    0.0000
7    BEN_RES_REG      BIGINT           0    0.0000
8    BEN_SEX_COD      BIGINT           0    0.0000
9        CPL_COD      BIGINT           0    0.0000
10   CPT_ENV_TYP      BIGINT           0    0.0000
11   DDP_SPE_COD      BIGINT           0    0.0000
12   DRG_AFF_NAT      BIGINT           0    0.0000
13   ETB_DCS_MCO     VARCHAR           0    0.0000
14  ETE_CAT_SNDS      BIGINT           0    0.0000
15   ETE_IND_TAA      BIGINT           0    0.0000
16   ETE_REG_COD      BIGINT           0    0.0000
17  ETE_TYP_SNDS      BIGINT           0    0.0000
18  ETP_CAT_SNDS      BIGINT           0    0.0000
19   ETP_REG_COD      BIGINT           0    0.0000
20   EXE_INS_REG      BIGINT           0    0.0000
21       EXO_MTF      BIGINT           0    0.0000
22   FLT_ACT_COG      DOUBLE           0    0.0000
23   FLT_ACT_QTE      BIGINT           0    0.0000
24   FLT_DEP_MNT      DOUBLE           0    0.0000
25   FLT_PAI_MNT      DOUBLE           0    0.0000
26   FLT_REM_MNT      DOUBLE           0    0.0000
27   FLX_ANN_MOI      BIGINT           0    0.0000
28   MDT_TYP_COD      BIGINT           0    0.0000
29       MFT_COD      BIGINT           0    0.0000
30       MTM_NAT      BIGINT           0    0.0000
31   ORG_CLE_REG      BIGINT           0    0.0000
32   PRE_INS_REG      BIGINT           0    0.0000
33   PRS_ACT_COG      DOUBLE           0    0.0000
34   PRS_ACT_QTE      BIGINT           0    0.0000
35   PRS_DEP_MNT      DOUBLE           0    0.0000
36   PRS_FJH_TYP      BIGINT           0    0.0000
37       PRS_NAT      BIGINT           0    0.0000
38   PRS_PAI_MNT      DOUBLE           0    0.0000
39   PRS_PDS_QCP      BIGINT           0    0.0000
40   PRS_PPU_SEC      BIGINT           0    0.0000
41   PRS_REM_BSE      DOUBLE           0    0.0000
42   PRS_REM_MNT      DOUBLE           0    0.0000
43   PRS_REM_TAU      DOUBLE           0    0.0000
44   PRS_REM_TYP      BIGINT           0    0.0000
45   PSE_ACT_CAT      BIGINT           0    0.0000
46  PSE_ACT_SNDS      BIGINT           0    0.0000
47  PSE_SPE_SNDS      BIGINT           0    0.0000
48  PSE_STJ_SNDS      BIGINT           0    0.0000
49   PSP_ACT_CAT      BIGINT           0    0.0000
50  PSP_ACT_SNDS      BIGINT           0    0.0000
51  PSP_SPE_SNDS      BIGINT           0    0.0000
52  PSP_STJ_SNDS      BIGINT           0    0.0000
53       SOI_ANN     VARCHAR           0    0.0000
54       SOI_MOI     VARCHAR           0    0.0000
55   TOP_PS5_TRG      BIGINT           0    0.0000

In [9]:
nulls_with_dict_df = (
    nulls_long_df[nulls_long_df["null_count"] > 0]
    .merge(dict_df[["column_name", "label", "family", "description"]], on="column_name", how="left")
)

nulls_with_dict_df

   column_name column_type  null_count  null_pct label family description
0  PRS_ACT_NBR      BIGINT     4120235   12.0589   NaN    NaN         NaN
1  FLT_ACT_NBR      BIGINT     3788351   11.0876   NaN    NaN         NaN

### Lecture utile des nulls observés

Les deux colonnes de dénombrement les plus sensibles sont généralement :

- **`PRS_ACT_NBR`** : dénombrement brut.  
  Le dictionnaire précise qu'il faut filtrer correctement le type de remboursement et qu'il faut **privilégier la quantité au dénombrement**, car le dénombrement n'est pas remonté pour l'ensemble des régimes.

- **`FLT_ACT_NBR`** : dénombrement préfiltré.  
  Cette variable évite déjà le double comptage lié au type de remboursement, mais elle reste partiellement renseignée car le dénombrement n'est pas disponible sur tout le périmètre.

Donc :
- beaucoup de nulls sur ces colonnes ne veulent **pas forcément** dire que la donnée est mauvaise ;
- cela peut simplement traduire une **limite de couverture métier** ;
- pour une analyse globale, il faut souvent préférer les variables de **quantité** (`*_QTE`) aux variables de **dénombrement** (`*_NBR`).

## 6. Doublons exacts de lignes — définition correcte

Ici, un doublon signifie :

> deux lignes ou plus strictement identiques sur **toutes** les colonnes analysées.

Important :
- les `NULL` comptent dans la comparaison ;
- deux lignes sont doublons si elles ont les **mêmes valeurs partout** et les `NULL` aux **mêmes endroits** ;

Exemple :
- ligne A = `(1, NULL, 202505)`  
- ligne B = `(1, NULL, 202505)`  
  → doublon exact

- ligne A = `(1, NULL, 202505)`  
- ligne B = `(1, 0, 202505)`  
  → **pas** un doublon

In [10]:
duplicates_df = con.execute(f'''
WITH groupes AS (
    SELECT *, COUNT(*) AS cnt
    FROM {table_name}
    GROUP BY ALL
    HAVING COUNT(*) > 1
)
SELECT
    COUNT(*) AS nb_groupes_doublons,
    COALESCE(SUM(cnt - 1), 0) AS nb_lignes_dupliquees,
    COALESCE(SUM(cnt), 0) AS nb_lignes_concernees
FROM groupes
''').df()

duplicates_df

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   nb_groupes_doublons  nb_lignes_dupliquees  nb_lignes_concernees
0                    0                   0.0                   0.0

## 7. Exemples concrets de doublons

Cette cellule affiche des groupes de lignes dupliquées avec :
- `nb_occurrences` = nombre de fois où la ligne identique apparaît ;
- `nb_nulls_ligne` = nombre de colonnes nulles dans cette ligne.

In [11]:
null_count_expr = " + ".join([f'CASE WHEN "{col}" IS NULL THEN 1 ELSE 0 END' for col in columns])

duplicate_examples_df = con.execute(f'''
SELECT
    *,
    COUNT(*) AS nb_occurrences,
    ({null_count_expr}) AS nb_nulls_ligne
FROM {table_name}
GROUP BY ALL
HAVING COUNT(*) > 1
ORDER BY nb_occurrences DESC, nb_nulls_ligne DESC
LIMIT 20
''').df()

duplicate_examples_df

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Empty DataFrame
Columns: [FLX_ANN_MOI, ORG_CLE_REG, AGE_BEN_SNDS, BEN_RES_REG, BEN_CMU_TOP, BEN_QLT_COD, BEN_SEX_COD, DDP_SPE_COD, ETE_CAT_SNDS, ETE_REG_COD, ETE_TYP_SNDS, ETP_REG_COD, ETP_CAT_SNDS, MDT_TYP_COD, MFT_COD, PRS_FJH_TYP, PRS_ACT_COG, PRS_ACT_NBR, PRS_ACT_QTE, PRS_DEP_MNT, PRS_PAI_MNT, PRS_REM_BSE, PRS_REM_MNT, FLT_ACT_COG, FLT_ACT_NBR, FLT_ACT_QTE, FLT_PAI_MNT, FLT_DEP_MNT, FLT_REM_MNT, SOI_ANN, SOI_MOI, ASU_NAT, ATT_NAT, CPL_COD, CPT_ENV_TYP, DRG_AFF_NAT, ETE_IND_TAA, EXO_MTF, MTM_NAT, PRS_NAT, PRS_PPU_SEC, PRS_REM_TAU, PRS_REM_TYP, PRS_PDS_QCP, EXE_INS_REG, PSE_ACT_SNDS, PSE_ACT_CAT, PSE_SPE_SNDS, PSE_STJ_SNDS, PRE_INS_REG, PSP_ACT_SNDS, PSP_ACT_CAT, PSP_SPE_SNDS, PSP_STJ_SNDS, TOP_PS5_TRG, ETB_DCS_MCO, nb_occurrences, nb_nulls_ligne]
Index: []

[0 rows x 58 columns]

## 8. Analyse détaillée par colonne

Pour chaque colonne :
- type ;
- nombre de valeurs non nulles ;
- nombre de nulls ;
- pourcentage de nulls ;
- nombre de valeurs distinctes non nulles.

Attention :
- `COUNT(DISTINCT ...)` peut être coûteux sur un très gros fichier ;
- sur 6 Go, cette cellule peut prendre du temps.

In [13]:
detail_rows = []

for col in columns:
    q = f'''
    SELECT
        COUNT(*) AS row_count,
        COUNT("{col}") AS non_null_count,
        SUM(CASE WHEN "{col}" IS NULL THEN 1 ELSE 0 END) AS null_count,
        COUNT(DISTINCT "{col}") AS distinct_non_null_count
    FROM {table_name}
    '''
    row = con.execute(q).fetchone()
    row_count, non_null_count, null_count, distinct_non_null_count = row
    detail_rows.append({
        "column_name": col,
        "column_type": column_types[col],
        "row_count": int(row_count),
        "non_null_count": int(non_null_count),
        "null_count": int(null_count),
        "null_pct": round((null_count / row_count * 100), 4) if row_count else 0.0,
        "distinct_non_null_count": int(distinct_non_null_count)
    })

detail_df = pd.DataFrame(detail_rows).sort_values(
    by=["null_count", "column_name"], ascending=[False, True]
).reset_index(drop=True)

detail_df

,column_name,column_type,row_count,non_null_count,null_count,null_pct,distinct_non_null_count
0,PRS_ACT_NBR,BIGINT,34167564,30047329,4120235,12.0589,18392
1,FLT_ACT_NBR,BIGINT,34167564,30379213,3788351,11.0876,17946
2,AGE_BEN_SNDS,BIGINT,34167564,34167564,0,0.0000,9
3,ASU_NAT,BIGINT,34167564,34167564,0,0.0000,11
4,ATT_NAT,BIGINT,34167564,34167564,0,0.0000,4
5,BEN_CMU_TOP,BIGINT,34167564,34167564,0,0.0000,4
6,BEN_QLT_COD,BIGINT,34167564,34167564,0,0.0000,5
7,BEN_RES_REG,BIGINT,34167564,34167564,0,0.0000,14
8,BEN_SEX_COD,BIGINT,34167564,34167564,0,0.0000,3
9,CPL_COD,BIGINT,34167564,34167564,0,0.0000,4
10,CPT_ENV_TYP,BIGINT,34167564,34167564,0,0.0000,9
11,DDP_SPE_COD,BIGINT,34167564,34167564,0,0.0000,32
12,DRG_AFF_NAT,BIGINT,34167564,34167564,0,0.0000,20
13,ETB_DCS_MCO,VARCHAR,34167564,34167564,0,0.0000,9
14,ETE_CAT_SNDS,BIGINT,34167564,34167564,0,0.0000,35
15,ETE_IND_TAA,BIGINT,34167564,34167564,0,0.0000,4
16,ETE_REG_COD,BIGINT,34167564,34167564,0,0.0000,14
17,ETE_TYP_SNDS,BIGINT,34167564,34167564,0,0.0000,5
18,ETP_CAT_SNDS,BIGINT,34167564,34167564,0,0.0000,46
19,ETP_REG_COD,BIGINT,34167564,34167564,0,0.0000,14
20,EXE_INS_REG,BIGINT,34167564,34167564,0,0.0000,14
21,EXO_MTF,BIGINT,34167564,34167564,0,0.0000,23
22,FLT_ACT_COG,DOUBLE,34167564,34167564,0,0.0000,127418
23,FLT_ACT_QTE,BIGINT,34167564,34167564,0,0.0000,19076
24,FLT_DEP_MNT,DOUBLE,34167564,34167564,0,0.0000,132532
25,FLT_PAI_MNT,DOUBLE,34167564,34167564,0,0.0000,685568
26,FLT_REM_MNT,DOUBLE,34167564,34167564,0,0.0000,721414
27,FLX_ANN_MOI,BIGINT,34167564,34167564,0,0.0000,1
28,MDT_TYP_COD,BIGINT,34167564,34167564,0,0.0000,4
29,MFT_COD,BIGINT,34167564,34167564,0,0.0000,21
30,MTM_NAT,BIGINT,34167564,34167564,0,0.0000,6
31,ORG_CLE_REG,BIGINT,34167564,34167564,0,0.0000,14
32,PRE_INS_REG,BIGINT,34167564,34167564,0,0.0000,14
33,PRS_ACT_COG,DOUBLE,34167564,34167564,0,0.0000,129288
34,PRS_ACT_QTE,BIGINT,34167564,34167564,0,0.0000,19589
35,PRS_DEP_MNT,DOUBLE,34167564,34167564,0,0.0000,133582
36,PRS_FJH_TYP,BIGINT,34167564,34167564,0,0.0000,5
37,PRS_NAT,BIGINT,34167564,34167564,0,0.0000,922
38,PRS_PAI_MNT,DOUBLE,34167564,34167564,0,0.0000,709517
39,PRS_PDS_QCP,BIGINT,34167564,34167564,0,0.0000,24
40,PRS_PPU_SEC,BIGINT,34167564,34167564,0,0.0000,2
41,PRS_REM_BSE,DOUBLE,34167564,34167564,0,0.0000,633350
42,PRS_REM_MNT,DOUBLE,34167564,34167564,0,0.0000,735933
43,PRS_REM_TAU,DOUBLE,34167564,34167564,0,0.0000,3442
44,PRS_REM_TYP,BIGINT,34167564,34167564,0,0.0000,10
45,PSE_ACT_CAT,BIGINT,34167564,34167564,0,0.0000,11
46,PSE_ACT_SNDS,BIGINT,34167564,34167564,0,0.0000,13
47,PSE_SPE_SNDS,BIGINT,34167564,34167564,0,0.0000,27
48,PSE_STJ_SNDS,BIGINT,34167564,34167564,0,0.0000,4
49,PSP_ACT_CAT,BIGINT,34167564,34167564,0,0.0000,11
50,PSP_ACT_SNDS,BIGINT,34167564,34167564,0,0.0000,13
51,PSP_SPE_SNDS,BIGINT,34167564,34167564,0,0.0000,27
52,PSP_STJ_SNDS,BIGINT,34167564,34167564,0,0.0000,4
53,SOI_ANN,VARCHAR,34167564,34167564,0,0.0000,26
54,SOI_MOI,VARCHAR,34167564,34167564,0,0.0000,13
55,TOP_PS5_TRG,BIGINT,34167564,34167564,0,0.0000,3

## 9. Résumé final consolidé

In [14]:
resume_df = global_df.copy()
resume_df["nb_groupes_doublons"] = int(duplicates_df.loc[0, "nb_groupes_doublons"])
resume_df["nb_lignes_dupliquees"] = int(duplicates_df.loc[0, "nb_lignes_dupliquees"])
resume_df["nb_lignes_concernees_par_doublons"] = int(duplicates_df.loc[0, "nb_lignes_concernees"])

resume_df

,nb_lignes,nb_colonnes,nb_cellules_total,nb_null_total,pct_null_global,nb_groupes_doublons,nb_lignes_dupliquees,nb_lignes_concernees_par_doublons
0,34167564,56,1913383584,7908586,0.4133,0,0,0